### ISSUE TITLE
Foundry Version 10 Update

### ISSUE THREAD

**Issue by TheMasterGeese** [TheMasterGeese/Discord-Integration#44]
Investigate what changes (if any) need to be made to accomodate V10, and implement them (or create a new issue to implement them.)

**Comment by Nephiaust** [comment]
I just installed it on v10. 

From Chrome's console log
` You are accessing the User#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.`

From the NodeJS console
`FoundryVTT | 2022-11-06 02:23:38 | [warn] The module "discord-integration" is using "name" which is deprecated in favor of "id"
Deprecated since Version 10
Backwards-compatible support will be removed in Version 13
FoundryVTT | 2022-11-06 02:23:38 | [warn] The module "discord-integration" is using "author" which is deprecated in favor of "authors"
Deprecated since Version 9
Backwards-compatible support will be removed in Version 11
FoundryVTT | 2022-11-06 02:23:38 | [warn] The module "discord-integration" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
Deprecated since Version 10
Backwards-compatible support will be removed in Version 13
`

**Comment by TheMasterGeese** [comment]
This has been fixed in the latest release v3.0.0.
